apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name | dump }}
  links:
  links:
    - url: https://admin.example-org.com
      title: ${{ values.name | dump }} Dashboard
      icon: dashboard
      type: admin-dashboard
  annotations:
    github.com/project-slug: ${{values.destination.owner + "/" + values.destination.repo}}
    backstage.io/techdocs-ref: dir:.
spec:
  type: website
  lifecycle: experimental
  owner: ${{values.owner | dump }}
