apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name | dump }}
  links:
    - url: https://admin.example-org.com
      title: Dashboard
      icon: dashboard
      type: admin-dashboard
  annotations:
    gitlab.com/project-slug: "jdf_projects/" + values.destination.repo}}
    gitlab.com/instance: gitlab.com
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: experimental
  owner: ${{values.owner | dump }}
